// Generated by scripts/build-seo.mjs.
const TRACKING_METADATA = {
  "pages": {
    "/": {
      "type": "home",
      "label": "Course directory"
    },
    "/indoor.html": {
      "type": "indoor",
      "label": "Indoor Golf"
    },
    "/about.html": {
      "type": "about",
      "label": "About"
    },
    "/golf-courses/new-philadelphia-oh/": {
      "type": "area",
      "label": "New Philadelphia / Dover"
    },
    "/golf-courses/canton-oh/": {
      "type": "area",
      "label": "Canton area"
    },
    "/golf-courses/akron-oh/": {
      "type": "area",
      "label": "Akron area"
    },
    "/golf-courses/youngstown-oh/": {
      "type": "area",
      "label": "Youngstown & the Mahoning Valley"
    },
    "/golf-courses/cleveland-west-oh/": {
      "type": "area",
      "label": "Cleveland West Side & Western Suburbs"
    },
    "/golf-courses/wooster-orrville-oh/": {
      "type": "area",
      "label": "Wooster, Orrville & nearby golf"
    },
    "/golf-courses/kent-ravenna-oh/": {
      "type": "area",
      "label": "Kent, Ravenna & Streetsboro"
    },
    "/golf-courses/zanesville-oh/": {
      "type": "area",
      "label": "Zanesville, Nashport & nearby golf"
    },
    "/golf-courses/mansfield-ashland-oh/": {
      "type": "area",
      "label": "Mansfield, Ashland & Bellville"
    },
    "/golf-courses/medina-hinckley-oh/": {
      "type": "area",
      "label": "Medina, Hinckley & Brunswick"
    },
    "/golf-courses/licking-county-oh/": {
      "type": "area",
      "label": "Licking County"
    },
    "/golf-courses/mount-vernon-howard-oh/": {
      "type": "area",
      "label": "Mount Vernon & Howard"
    },
    "/golf-courses/cleveland-east-oh/": {
      "type": "area",
      "label": "Cleveland East"
    },
    "/courses/oak-shadows-golf-club-new-philadelphia-oh/": {
      "type": "course",
      "courseId": "td-0002",
      "label": "Oak Shadows Golf Club"
    },
    "/courses/zoar-village-golf-course-zoar-oh/": {
      "type": "course",
      "courseId": "td-0001",
      "label": "Zoar Village Golf Course"
    },
    "/courses/spring-valley-golf-course-east-sparta-oh/": {
      "type": "course",
      "courseId": "td-0021",
      "label": "Spring Valley Golf Course"
    },
    "/courses/mill-creek-golf-course-boardman-oh/": {
      "type": "course",
      "courseId": "td-0069",
      "label": "Mill Creek Golf Course"
    },
    "/courses/wick-recreation-area-par-3-youngstown-oh/": {
      "type": "course",
      "courseId": "td-0099",
      "label": "Wick Recreation Area Par 3"
    },
    "/courses/round-lake-golf-course-lakeville-oh/": {
      "type": "course",
      "courseId": "td-0033",
      "label": "Round Lake Golf Course"
    },
    "/courses/sweetbriar-golf-club-avon-lake-oh/": {
      "type": "course",
      "courseId": "td-0046",
      "label": "Sweetbriar Golf Club"
    },
    "/courses/zanesville-jaycees-public-golf-course-zanesville-oh/": {
      "type": "course",
      "courseId": "td-0079",
      "label": "Zanesville Jaycees Public Golf Course"
    },
    "/courses/reserve-run-golf-course-poland-oh/": {
      "type": "course",
      "courseId": "td-0051",
      "label": "Reserve Run Golf Course"
    },
    "/courses/knoll-run-golf-course-lowellville-oh/": {
      "type": "course",
      "courseId": "td-0070",
      "label": "Knoll Run Golf Course"
    },
    "/courses/the-links-at-firestone-farms-columbiana-oh/": {
      "type": "course",
      "courseId": "td-0071",
      "label": "The Links at Firestone Farms"
    },
    "/courses/the-flying-b-golf-course-salem-oh/": {
      "type": "course",
      "courseId": "td-0050",
      "label": "The Flying B Golf Course"
    },
    "/courses/wilkshire-golf-course-bolivar-oh/": {
      "type": "course",
      "courseId": "td-0003",
      "label": "Wilkshire Golf Course"
    },
    "/courses/arrowhead-golf-club-and-banquet-center-north-canton-oh/": {
      "type": "course",
      "courseId": "td-0013",
      "label": "Arrowhead Golf Club & Banquet Center"
    },
    "/courses/mud-run-golf-course-akron-oh/": {
      "type": "course",
      "courseId": "td-0028",
      "label": "Mud Run Golf Course"
    },
    "/courses/tannenhauf-golf-club-alliance-oh/": {
      "type": "course",
      "courseId": "td-0031",
      "label": "Tannenhauf Golf Club"
    },
    "/courses/big-met-golf-course-fairview-park-oh/": {
      "type": "course",
      "courseId": "td-0054",
      "label": "Big Met Golf Course"
    },
    "/courses/little-met-golf-course-cleveland-oh/": {
      "type": "course",
      "courseId": "td-0056",
      "label": "Little Met Golf Course"
    },
    "/courses/mastick-woods-golf-course-cleveland-oh/": {
      "type": "course",
      "courseId": "td-0057",
      "label": "Mastick Woods Golf Course"
    },
    "/courses/meadowood-golf-course-westlake-oh/": {
      "type": "course",
      "courseId": "td-0112",
      "label": "Meadowood Golf Course"
    },
    "/courses/the-pines-golf-club-orrville-oh/": {
      "type": "course",
      "courseId": "td-0019",
      "label": "The Pines Golf Club"
    },
    "/courses/chippewa-golf-club-doylestown-oh/": {
      "type": "course",
      "courseId": "td-0020",
      "label": "Chippewa Golf Club"
    },
    "/courses/riceland-golf-course-orrville-oh/": {
      "type": "course",
      "courseId": "td-0032",
      "label": "Riceland Golf Course"
    },
    "/courses/l-c-boles-memorial-golf-course-wooster-oh/": {
      "type": "course",
      "courseId": "td-0113",
      "label": "L.C. Boles Memorial Golf Course"
    },
    "/courses/windmill-lakes-golf-club-ravenna-oh/": {
      "type": "course",
      "courseId": "td-0036",
      "label": "Windmill Lakes Golf Club"
    },
    "/courses/boulder-creek-golf-club-streetsboro-oh/": {
      "type": "course",
      "courseId": "td-0041",
      "label": "Boulder Creek Golf Club"
    },
    "/courses/paradise-lake-country-club-suffield-oh/": {
      "type": "course",
      "courseId": "td-0121",
      "label": "Paradise Lake Country Club"
    },
    "/courses/the-fairways-at-twin-lakes-kent-oh/": {
      "type": "course",
      "courseId": "td-0122",
      "label": "The Fairways at Twin Lakes"
    },
    "/courses/raccoon-hill-golf-club-kent-oh/": {
      "type": "course",
      "courseId": "td-0123",
      "label": "Raccoon Hill Golf Club"
    },
    "/courses/eaglesticks-golf-club-zanesville-oh/": {
      "type": "course",
      "courseId": "td-0076",
      "label": "EagleSticks Golf Club"
    },
    "/courses/crystal-springs-golf-club-hopewell-oh/": {
      "type": "course",
      "courseId": "td-0077",
      "label": "Crystal Springs Golf Club"
    },
    "/courses/the-virtues-golf-club-nashport-oh/": {
      "type": "course",
      "courseId": "td-0078",
      "label": "The Virtues Golf Club"
    },
    "/courses/vista-golf-course-nashport-oh/": {
      "type": "course",
      "courseId": "td-0081",
      "label": "Vista Golf Course"
    },
    "/courses/wildfire-golf-club-new-concord-oh/": {
      "type": "course",
      "courseId": "td-0098",
      "label": "Wildfire Golf Club"
    },
    "/courses/deer-ridge-golf-club-bellville-oh/": {
      "type": "course",
      "courseId": "td-0048",
      "label": "Deer Ridge Golf Club"
    },
    "/courses/little-apple-golf-course-bellville-oh/": {
      "type": "course",
      "courseId": "td-0110",
      "label": "Little Apple Golf Course"
    },
    "/courses/brookside-golf-course-ashland-oh/": {
      "type": "course",
      "courseId": "td-0115",
      "label": "Brookside Golf Course"
    },
    "/courses/ashland-golf-club-ashland-oh/": {
      "type": "course",
      "courseId": "td-0116",
      "label": "Ashland Golf Club"
    },
    "/courses/forest-hills-golf-course-mansfield-oh/": {
      "type": "course",
      "courseId": "td-0118",
      "label": "Forest Hills Golf Course"
    },
    "/courses/twin-lakes-golf-club-mansfield-oh/": {
      "type": "course",
      "courseId": "td-0124",
      "label": "Twin Lakes Golf Club"
    },
    "/courses/pine-hills-golf-club-hinckley-oh/": {
      "type": "course",
      "courseId": "td-0042",
      "label": "Pine Hills Golf Club"
    },
    "/courses/bunker-hill-golf-course-medina-oh/": {
      "type": "course",
      "courseId": "td-0043",
      "label": "Bunker Hill Golf Course"
    },
    "/courses/coppertop-golf-club-valley-city-oh/": {
      "type": "course",
      "courseId": "td-0044",
      "label": "Coppertop Golf Club"
    },
    "/courses/ironwood-golf-course-hinckley-oh/": {
      "type": "course",
      "courseId": "td-0055",
      "label": "Ironwood Golf Course"
    },
    "/courses/shale-creek-golf-club-medina-oh/": {
      "type": "course",
      "courseId": "td-0061",
      "label": "Shale Creek Golf Club"
    },
    "/courses/valleaire-golf-club-hinckley-oh/": {
      "type": "course",
      "courseId": "td-0062",
      "label": "Valleaire Golf Club"
    },
    "/courses/hinckley-hills-golf-course-hinckley-oh/": {
      "type": "course",
      "courseId": "td-0065",
      "label": "Hinckley Hills Golf Course"
    },
    "/courses/cossett-creek-golf-course-brunswick-oh/": {
      "type": "course",
      "courseId": "td-0066",
      "label": "Cossett Creek Golf Course"
    },
    "/courses/denison-golf-club-granville-oh/": {
      "type": "course",
      "courseId": "td-0087",
      "label": "Denison Golf Club"
    },
    "/courses/mastodon-golf-club-heath-oh/": {
      "type": "course",
      "courseId": "td-0088",
      "label": "Mastodon Golf Club"
    },
    "/courses/raccoon-valley-golf-club-granville-oh/": {
      "type": "course",
      "courseId": "td-0089",
      "label": "Raccoon Valley Golf Club"
    },
    "/courses/the-links-at-echo-springs-johnstown-oh/": {
      "type": "course",
      "courseId": "td-0090",
      "label": "The Links at Echo Springs"
    },
    "/courses/cumberland-trail-golf-club-pataskala-oh/": {
      "type": "course",
      "courseId": "td-0091",
      "label": "Cumberland Trail Golf Club"
    },
    "/courses/clover-valley-golf-club-johnstown-oh/": {
      "type": "course",
      "courseId": "td-0094",
      "label": "Clover Valley Golf Club"
    },
    "/courses/kyber-run-golf-course-johnstown-oh/": {
      "type": "course",
      "courseId": "td-0095",
      "label": "Kyber Run Golf Course"
    },
    "/courses/irish-hills-golf-club-mount-vernon-oh/": {
      "type": "course",
      "courseId": "td-0092",
      "label": "Irish Hills Golf Club"
    },
    "/courses/apple-valley-golf-club-howard-oh/": {
      "type": "course",
      "courseId": "td-0114",
      "label": "Apple Valley Golf Club"
    },
    "/courses/vernon-view-golf-course-mount-vernon-oh/": {
      "type": "course",
      "courseId": "td-0119",
      "label": "Vernon View Golf Course"
    },
    "/courses/chapel-hill-golf-course-mount-vernon-oh/": {
      "type": "course",
      "courseId": "td-0120",
      "label": "Chapel Hill Golf Course"
    },
    "/courses/manakiki-golf-course-willoughby-hills-oh/": {
      "type": "course",
      "courseId": "td-0049",
      "label": "Manakiki Golf Course"
    },
    "/courses/st-denis-golf-club-chardon-oh/": {
      "type": "course",
      "courseId": "td-0053",
      "label": "St. Denis Golf Club"
    },
    "/courses/fowler-s-mill-golf-course-chesterland-oh/": {
      "type": "course",
      "courseId": "td-0067",
      "label": "Fowler's Mill Golf Course"
    },
    "/courses/painesville-country-club-painesville-oh/": {
      "type": "course",
      "courseId": "td-0068",
      "label": "Painesville Country Club"
    },
    "/courses/pleasant-hill-golf-course-chardon-chardon-oh/": {
      "type": "course",
      "courseId": "td-0074",
      "label": "Pleasant Hill Golf Course — Chardon"
    }
  },
  "courseKeys": {
    "Zoar Village Golf Course\nZoar, OH": "td-0001",
    "Oak Shadows Golf Club\nNew Philadelphia, OH": "td-0002",
    "Wilkshire Golf Course\nBolivar, OH": "td-0003",
    "River Greens Golf Course\nWest Lafayette, OH": "td-0004",
    "Hickory Flats Golf Course\nWest Lafayette, OH": "td-0005",
    "The Legends of Massillon\nMassillon, OH": "td-0006",
    "Five Waters Golf Course\nMidvale, OH": "td-0007",
    "Big Bend Golf Course\nUhrichsville, OH": "td-0008",
    "Black Gold Golf Club\nSugarcreek, OH": "td-0009",
    "The Quarry Golf Club and Venue\nCanton, OH": "td-0010",
    "Carroll Meadows Golf Course\nCarrollton, OH": "td-0011",
    "Great Trail Golf Course\nMinerva, OH": "td-0012",
    "Arrowhead Golf Club & Banquet Center\nNorth Canton, OH": "td-0013",
    "Raintree Golf & Event Center\nUniontown, OH": "td-0014",
    "Raymond C. Firestone Golf Course\nAkron, OH": "td-0015",
    "Sable Creek Golf Course\nHartville, OH": "td-0016",
    "Pleasant View Golf Club\nParis, OH": "td-0017",
    "Fire Ridge Golf Course\nMillersburg, OH": "td-0018",
    "The Pines Golf Club\nOrrville, OH": "td-0019",
    "Chippewa Golf Club\nDoylestown, OH": "td-0020",
    "Spring Valley Golf Course\nEast Sparta, OH": "td-0021",
    "Clearview Golf Club\nEast Canton, OH": "td-0022",
    "Edgewater Golf Course\nMinerva, OH": "td-0023",
    "The Elms Country Club\nNorth Lawrence, OH": "td-0024",
    "Black Diamond Golf Course\nMillersburg, OH": "td-0025",
    "Mayfair Country Club\nGreen, OH": "td-0026",
    "Chenoweth Golf Course\nAkron, OH": "td-0027",
    "Mud Run Golf Course\nAkron, OH": "td-0028",
    "J. Edward Good Park Golf Course\nAkron, OH": "td-0029",
    "Meadowlake Golf Course\nCanton, OH": "td-0030",
    "Tannenhauf Golf Club\nAlliance, OH": "td-0031",
    "Riceland Golf Course\nOrrville, OH": "td-0032",
    "Round Lake Golf Course\nLakeville, OH": "td-0033",
    "Salt Fork State Park Golf Course\nLore City, OH": "td-0034",
    "Mulligan Springs Golf Course\nMogadore, OH": "td-0035",
    "Windmill Lakes Golf Club\nRavenna, OH": "td-0036",
    "Turkeyfoot Lake Golf Links\nAkron, OH": "td-0037",
    "Brookledge Golf Club\nCuyahoga Falls, OH": "td-0038",
    "Fox Den Golf Course\nStow, OH": "td-0039",
    "Roses Run Country Club\nStow, OH": "td-0040",
    "Boulder Creek Golf Club\nStreetsboro, OH": "td-0041",
    "Pine Hills Golf Club\nHinckley, OH": "td-0042",
    "Bunker Hill Golf Course\nMedina, OH": "td-0043",
    "Coppertop Golf Club\nValley City, OH": "td-0044",
    "Grey Hawk Golf Club\nLaGrange, OH": "td-0045",
    "Sweetbriar Golf Club\nAvon Lake, OH": "td-0046",
    "Pleasant Hill Golf Course\nPerrysville, OH": "td-0047",
    "Deer Ridge Golf Club\nBellville, OH": "td-0048",
    "Manakiki Golf Course\nWilloughby Hills, OH": "td-0049",
    "The Flying B Golf Course\nSalem, OH": "td-0050",
    "Reserve Run Golf Course\nPoland, OH": "td-0051",
    "Sleepy Hollow Golf Course\nBrecksville, OH": "td-0052",
    "St. Denis Golf Club\nChardon, OH": "td-0053",
    "Big Met Golf Course\nFairview Park, OH": "td-0054",
    "Ironwood Golf Course\nHinckley, OH": "td-0055",
    "Little Met Golf Course\nCleveland, OH": "td-0056",
    "Mastick Woods Golf Course\nCleveland, OH": "td-0057",
    "Seneca Golf Course\nBroadview Heights, OH": "td-0058",
    "Shawnee Hills Golf Course\nBedford, OH": "td-0059",
    "Washington Golf Course\nNewburgh Heights, OH": "td-0060",
    "Shale Creek Golf Club\nMedina, OH": "td-0061",
    "Valleaire Golf Club\nHinckley, OH": "td-0062",
    "Mallard Creek Golf Club\nColumbia Station, OH": "td-0063",
    "Pine Brook Golf Links\nGrafton, OH": "td-0064",
    "Hinckley Hills Golf Course\nHinckley, OH": "td-0065",
    "Cossett Creek Golf Course\nBrunswick, OH": "td-0066",
    "Fowler's Mill Golf Course\nChesterland, OH": "td-0067",
    "Painesville Country Club\nPainesville, OH": "td-0068",
    "Mill Creek Golf Course\nBoardman, OH": "td-0069",
    "Knoll Run Golf Course\nLowellville, OH": "td-0070",
    "The Links at Firestone Farms\nColumbiana, OH": "td-0071",
    "Lake Milton Golf Club\nLake Milton, OH": "td-0072",
    "Lyons Den Golf\nCanal Fulton, OH": "td-0073",
    "Pleasant Hill Golf Course — Chardon\nChardon, OH": "td-0074",
    "Olde Dutch Mill Golf Course\nLake Milton, OH": "td-0075",
    "EagleSticks Golf Club\nZanesville, OH": "td-0076",
    "Crystal Springs Golf Club\nHopewell, OH": "td-0077",
    "The Virtues Golf Club\nNashport, OH": "td-0078",
    "Zanesville Jaycees Public Golf Course\nZanesville, OH": "td-0079",
    "Fuller's Fairways\nZanesville, OH": "td-0080",
    "Vista Golf Course\nNashport, OH": "td-0081",
    "Cadiz Country Club\nCadiz, OH": "td-0082",
    "Beaver Creek Meadows Golf Course\nLisbon, OH": "td-0083",
    "Turkana Golf Course\nEast Liverpool, OH": "td-0084",
    "Historic Highlands Golf Course\nEast Liverpool, OH": "td-0085",
    "East Palestine Country Club\nNegley, OH": "td-0086",
    "Denison Golf Club\nGranville, OH": "td-0087",
    "Mastodon Golf Club\nHeath, OH": "td-0088",
    "Raccoon Valley Golf Club\nGranville, OH": "td-0089",
    "The Links at Echo Springs\nJohnstown, OH": "td-0090",
    "Cumberland Trail Golf Club\nPataskala, OH": "td-0091",
    "Irish Hills Golf Club\nMount Vernon, OH": "td-0092",
    "Lancaster Golf Club\nLancaster, OH": "td-0093",
    "Clover Valley Golf Club\nJohnstown, OH": "td-0094",
    "Kyber Run Golf Course\nJohnstown, OH": "td-0095",
    "Coyote Run Golf Course\nThornville, OH": "td-0096",
    "Harbor Hills Country Club\nHebron, OH": "td-0097",
    "Wildfire Golf Club\nNew Concord, OH": "td-0098",
    "Wick Recreation Area Par 3\nYoungstown, OH": "td-0099",
    "Wilson Road Golf Course\nColumbus, OH": "td-0100",
    "Blacklick Woods Golf Course\nReynoldsburg, OH": "td-0101",
    "Little Bear Golf Club\nLewis Center, OH": "td-0102",
    "Robin’s Nest Par 3\nCleves, OH": "td-0103",
    "Little Miami Golf Center\nNewtown, OH": "td-0104",
    "Meadow Links & Golf Academy\nCincinnati, OH": "td-0105",
    "Green Hills Golf Course\nClyde, OH": "td-0106",
    "Wee Links at SportsOhio\nDublin, OH": "td-0107",
    "Fernbank Golf Course\nCincinnati, OH": "td-0108",
    "Reeves Golf Course\nCincinnati, OH": "td-0109",
    "Little Apple Golf Course\nBellville, OH": "td-0110",
    "Armco Park Golf Course\nLebanon, OH": "td-0111",
    "Meadowood Golf Course\nWestlake, OH": "td-0112",
    "L.C. Boles Memorial Golf Course\nWooster, OH": "td-0113",
    "Apple Valley Golf Club\nHoward, OH": "td-0114",
    "Brookside Golf Course\nAshland, OH": "td-0115",
    "Ashland Golf Club\nAshland, OH": "td-0116",
    "Oak Tree Golf Club\nMansfield, OH": "td-0117",
    "Forest Hills Golf Course\nMansfield, OH": "td-0118",
    "Vernon View Golf Course\nMount Vernon, OH": "td-0119",
    "Chapel Hill Golf Course\nMount Vernon, OH": "td-0120",
    "Paradise Lake Country Club\nSuffield, OH": "td-0121",
    "The Fairways at Twin Lakes\nKent, OH": "td-0122",
    "Raccoon Hill Golf Club\nKent, OH": "td-0123",
    "Twin Lakes Golf Club\nMansfield, OH": "td-0124"
  },
  "allowed": {
    "/": [
      "td-0001:booking",
      "td-0002:booking",
      "td-0003:booking",
      "td-0004:booking",
      "td-0005:booking",
      "td-0006:booking",
      "td-0007:course_info",
      "td-0008:course_info",
      "td-0009:booking",
      "td-0010:booking",
      "td-0011:booking",
      "td-0012:booking",
      "td-0013:booking",
      "td-0014:booking",
      "td-0015:booking",
      "td-0016:booking",
      "td-0017:booking",
      "td-0018:course_info",
      "td-0019:booking",
      "td-0020:booking",
      "td-0021:booking",
      "td-0022:course_info",
      "td-0023:booking",
      "td-0024:course_info",
      "td-0025:course_info",
      "td-0026:booking",
      "td-0027:booking",
      "td-0028:booking",
      "td-0029:booking",
      "td-0030:booking",
      "td-0031:booking",
      "td-0032:booking",
      "td-0033:course_info",
      "td-0034:booking",
      "td-0035:course_info",
      "td-0036:booking",
      "td-0037:booking",
      "td-0038:booking",
      "td-0039:booking",
      "td-0040:booking",
      "td-0041:booking",
      "td-0042:booking",
      "td-0043:booking",
      "td-0044:booking",
      "td-0045:booking",
      "td-0046:booking",
      "td-0047:course_info",
      "td-0048:booking",
      "td-0049:booking",
      "td-0050:booking",
      "td-0051:booking",
      "td-0052:booking",
      "td-0053:booking",
      "td-0054:booking",
      "td-0055:booking",
      "td-0056:booking",
      "td-0057:booking",
      "td-0058:booking",
      "td-0059:booking",
      "td-0060:booking",
      "td-0061:booking",
      "td-0062:booking",
      "td-0063:booking",
      "td-0064:booking",
      "td-0065:booking",
      "td-0066:booking",
      "td-0067:booking",
      "td-0068:booking",
      "td-0069:course_updates",
      "td-0070:booking",
      "td-0071:booking",
      "td-0072:booking",
      "td-0073:course_info",
      "td-0074:booking",
      "td-0075:booking",
      "td-0076:booking",
      "td-0077:booking",
      "td-0078:booking",
      "td-0079:booking",
      "td-0080:course_info",
      "td-0081:booking",
      "td-0082:course_info",
      "td-0083:course_info",
      "td-0084:course_info",
      "td-0085:course_info",
      "td-0086:course_info",
      "td-0087:booking",
      "td-0088:booking",
      "td-0089:booking",
      "td-0090:booking",
      "td-0091:booking",
      "td-0092:booking",
      "td-0093:booking",
      "td-0094:booking",
      "td-0095:booking",
      "td-0096:booking",
      "td-0097:booking",
      "td-0098:course_info",
      "td-0099:course_info",
      "td-0100:booking",
      "td-0101:booking",
      "td-0102:booking",
      "td-0103:booking",
      "td-0104:booking",
      "td-0105:booking",
      "td-0106:booking",
      "td-0107:course_info",
      "td-0108:course_info",
      "td-0109:booking",
      "td-0110:booking",
      "td-0111:course_info",
      "td-0112:course_info",
      "td-0113:course_info",
      "td-0114:booking",
      "td-0115:booking",
      "td-0116:booking",
      "td-0117:booking",
      "td-0118:booking",
      "td-0119:booking",
      "td-0120:booking",
      "td-0121:booking",
      "td-0122:booking",
      "td-0123:booking",
      "td-0124:course_info"
    ],
    "/indoor.html": [
      "indoor-0001:booking",
      "indoor-0002:course_info",
      "indoor-0003:course_info",
      "indoor-0004:course_info",
      "indoor-0005:booking",
      "indoor-0006:booking",
      "indoor-0007:booking",
      "indoor-0008:booking",
      "indoor-0009:booking",
      "indoor-0010:booking",
      "indoor-0011:booking",
      "indoor-0012:booking",
      "indoor-0013:course_info",
      "indoor-0014:booking"
    ],
    "/golf-courses/new-philadelphia-oh/": [
      "td-0002:booking",
      "td-0002:rate_source",
      "td-0001:booking",
      "td-0001:rate_source",
      "td-0003:booking",
      "td-0003:rate_source",
      "td-0007:course_info",
      "td-0008:course_info",
      "td-0008:rate_source",
      "td-0009:booking",
      "td-0009:rate_source",
      "td-0021:booking",
      "td-0021:rate_source"
    ],
    "/golf-courses/canton-oh/": [
      "td-0030:booking",
      "td-0030:rate_source",
      "td-0010:booking",
      "td-0010:rate_source",
      "td-0013:booking",
      "td-0013:rate_source",
      "td-0014:booking",
      "td-0014:rate_source",
      "td-0016:booking",
      "td-0016:rate_source",
      "td-0022:course_info",
      "td-0022:rate_source",
      "td-0017:booking",
      "td-0017:rate_source",
      "td-0031:booking",
      "td-0031:rate_source",
      "td-0006:booking",
      "td-0006:rate_source",
      "td-0024:course_info",
      "td-0024:rate_source",
      "td-0073:course_info",
      "td-0021:booking",
      "td-0021:rate_source"
    ],
    "/golf-courses/akron-oh/": [
      "td-0029:booking",
      "td-0029:rate_source",
      "td-0028:booking",
      "td-0028:rate_source",
      "td-0027:booking",
      "td-0027:rate_source",
      "td-0015:booking",
      "td-0015:rate_source",
      "td-0037:booking",
      "td-0037:rate_source",
      "td-0026:booking",
      "td-0026:rate_source",
      "td-0035:course_info",
      "td-0038:booking",
      "td-0038:rate_source",
      "td-0039:booking",
      "td-0039:rate_source",
      "td-0040:booking",
      "td-0040:rate_source"
    ],
    "/golf-courses/youngstown-oh/": [
      "td-0099:course_info",
      "td-0099:rate_source",
      "td-0069:course_updates",
      "td-0051:booking",
      "td-0051:rate_source",
      "td-0070:booking",
      "td-0070:rate_source",
      "td-0071:booking",
      "td-0071:rate_source",
      "td-0050:booking",
      "td-0050:rate_source",
      "td-0072:booking",
      "td-0072:rate_source",
      "td-0075:booking",
      "td-0075:rate_source"
    ],
    "/golf-courses/cleveland-west-oh/": [
      "td-0054:booking",
      "td-0054:rate_source",
      "td-0056:booking",
      "td-0056:rate_source",
      "td-0057:booking",
      "td-0057:rate_source",
      "td-0112:course_info",
      "td-0112:rate_source",
      "td-0046:booking",
      "td-0046:rate_source",
      "td-0063:booking",
      "td-0063:rate_source",
      "td-0064:booking",
      "td-0064:rate_source",
      "td-0045:booking",
      "td-0045:rate_source"
    ],
    "/golf-courses/wooster-orrville-oh/": [
      "td-0113:course_info",
      "td-0113:rate_source",
      "td-0019:booking",
      "td-0019:rate_source",
      "td-0032:booking",
      "td-0032:rate_source",
      "td-0020:booking",
      "td-0020:rate_source",
      "td-0033:course_info",
      "td-0033:rate_source",
      "td-0018:course_info",
      "td-0018:rate_source",
      "td-0025:course_info",
      "td-0025:rate_source"
    ],
    "/golf-courses/kent-ravenna-oh/": [
      "td-0036:booking",
      "td-0036:rate_source",
      "td-0041:booking",
      "td-0041:rate_source",
      "td-0122:booking",
      "td-0122:rate_source",
      "td-0123:booking",
      "td-0123:rate_source",
      "td-0121:booking",
      "td-0121:rate_source"
    ],
    "/golf-courses/zanesville-oh/": [
      "td-0076:booking",
      "td-0076:rate_source",
      "td-0079:booking",
      "td-0079:rate_source",
      "td-0078:booking",
      "td-0078:rate_source",
      "td-0081:booking",
      "td-0081:rate_source",
      "td-0077:booking",
      "td-0077:rate_source",
      "td-0098:course_info",
      "td-0098:rate_source"
    ],
    "/golf-courses/mansfield-ashland-oh/": [
      "td-0118:booking",
      "td-0118:rate_source",
      "td-0124:course_info",
      "td-0124:rate_source",
      "td-0117:booking",
      "td-0117:rate_source",
      "td-0115:booking",
      "td-0115:rate_source",
      "td-0116:booking",
      "td-0116:rate_source",
      "td-0048:booking",
      "td-0048:rate_source",
      "td-0110:booking",
      "td-0110:rate_source",
      "td-0047:course_info",
      "td-0047:rate_source"
    ],
    "/golf-courses/medina-hinckley-oh/": [
      "td-0043:booking",
      "td-0043:rate_source",
      "td-0061:booking",
      "td-0061:rate_source",
      "td-0042:booking",
      "td-0042:rate_source",
      "td-0055:booking",
      "td-0055:rate_source",
      "td-0062:booking",
      "td-0062:rate_source",
      "td-0065:booking",
      "td-0065:rate_source",
      "td-0066:booking",
      "td-0066:rate_source",
      "td-0044:booking",
      "td-0044:rate_source"
    ],
    "/golf-courses/licking-county-oh/": [
      "td-0087:booking",
      "td-0087:rate_source",
      "td-0089:booking",
      "td-0089:rate_source",
      "td-0088:booking",
      "td-0088:rate_source",
      "td-0090:booking",
      "td-0090:rate_source",
      "td-0094:booking",
      "td-0094:rate_source",
      "td-0095:booking",
      "td-0095:rate_source",
      "td-0091:booking",
      "td-0091:rate_source"
    ],
    "/golf-courses/mount-vernon-howard-oh/": [
      "td-0092:booking",
      "td-0092:rate_source",
      "td-0119:booking",
      "td-0119:rate_source",
      "td-0120:booking",
      "td-0120:rate_source",
      "td-0114:booking",
      "td-0114:rate_source"
    ],
    "/golf-courses/cleveland-east-oh/": [
      "td-0049:booking",
      "td-0049:rate_source",
      "td-0067:booking",
      "td-0067:rate_source",
      "td-0053:booking",
      "td-0053:rate_source",
      "td-0074:booking",
      "td-0074:rate_source",
      "td-0068:booking",
      "td-0068:rate_source"
    ],
    "/courses/oak-shadows-golf-club-new-philadelphia-oh/": [
      "td-0002:rate_source",
      "td-0002:booking",
      "td-0007:course_info",
      "td-0008:course_info"
    ],
    "/courses/zoar-village-golf-course-zoar-oh/": [
      "td-0001:rate_source",
      "td-0001:booking"
    ],
    "/courses/spring-valley-golf-course-east-sparta-oh/": [
      "td-0021:rate_source",
      "td-0021:booking",
      "td-0010:booking",
      "td-0006:booking"
    ],
    "/courses/mill-creek-golf-course-boardman-oh/": [
      "td-0069:course_updates"
    ],
    "/courses/wick-recreation-area-par-3-youngstown-oh/": [
      "td-0099:rate_source",
      "td-0099:course_info"
    ],
    "/courses/round-lake-golf-course-lakeville-oh/": [
      "td-0033:rate_source",
      "td-0033:course_info",
      "td-0047:course_info",
      "td-0018:course_info",
      "td-0025:course_info"
    ],
    "/courses/sweetbriar-golf-club-avon-lake-oh/": [
      "td-0046:rate_source",
      "td-0046:booking"
    ],
    "/courses/zanesville-jaycees-public-golf-course-zanesville-oh/": [
      "td-0079:rate_source",
      "td-0079:booking",
      "td-0080:course_info"
    ],
    "/courses/reserve-run-golf-course-poland-oh/": [
      "td-0051:rate_source",
      "td-0051:booking"
    ],
    "/courses/knoll-run-golf-course-lowellville-oh/": [
      "td-0070:rate_source",
      "td-0070:booking"
    ],
    "/courses/the-links-at-firestone-farms-columbiana-oh/": [
      "td-0071:rate_source",
      "td-0071:booking",
      "td-0086:course_info"
    ],
    "/courses/the-flying-b-golf-course-salem-oh/": [
      "td-0050:rate_source",
      "td-0050:booking",
      "td-0072:booking"
    ],
    "/courses/wilkshire-golf-course-bolivar-oh/": [
      "td-0003:rate_source",
      "td-0003:booking"
    ],
    "/courses/arrowhead-golf-club-and-banquet-center-north-canton-oh/": [
      "td-0013:rate_source",
      "td-0013:booking",
      "td-0030:booking",
      "td-0026:booking",
      "td-0014:booking"
    ],
    "/courses/mud-run-golf-course-akron-oh/": [
      "td-0028:rate_source",
      "td-0028:booking",
      "td-0015:booking",
      "td-0037:booking",
      "td-0029:booking"
    ],
    "/courses/tannenhauf-golf-club-alliance-oh/": [
      "td-0031:rate_source",
      "td-0031:booking",
      "td-0016:booking",
      "td-0017:booking",
      "td-0030:booking"
    ],
    "/courses/big-met-golf-course-fairview-park-oh/": [
      "td-0054:rate_source",
      "td-0054:booking"
    ],
    "/courses/little-met-golf-course-cleveland-oh/": [
      "td-0056:rate_source",
      "td-0056:booking"
    ],
    "/courses/mastick-woods-golf-course-cleveland-oh/": [
      "td-0057:rate_source",
      "td-0057:booking"
    ],
    "/courses/meadowood-golf-course-westlake-oh/": [
      "td-0112:rate_source",
      "td-0112:course_info"
    ],
    "/courses/the-pines-golf-club-orrville-oh/": [
      "td-0019:rate_source",
      "td-0019:booking",
      "td-0024:course_info"
    ],
    "/courses/chippewa-golf-club-doylestown-oh/": [
      "td-0020:rate_source",
      "td-0020:booking",
      "td-0073:course_info",
      "td-0037:booking"
    ],
    "/courses/riceland-golf-course-orrville-oh/": [
      "td-0032:rate_source",
      "td-0032:booking",
      "td-0024:course_info"
    ],
    "/courses/l-c-boles-memorial-golf-course-wooster-oh/": [
      "td-0113:rate_source",
      "td-0113:course_info",
      "td-0025:course_info"
    ],
    "/courses/windmill-lakes-golf-club-ravenna-oh/": [
      "td-0036:rate_source",
      "td-0036:booking"
    ],
    "/courses/boulder-creek-golf-club-streetsboro-oh/": [
      "td-0041:rate_source",
      "td-0041:booking",
      "td-0039:booking"
    ],
    "/courses/paradise-lake-country-club-suffield-oh/": [
      "td-0121:rate_source",
      "td-0121:booking",
      "td-0035:course_info",
      "td-0016:booking",
      "td-0014:booking"
    ],
    "/courses/the-fairways-at-twin-lakes-kent-oh/": [
      "td-0122:rate_source",
      "td-0122:booking",
      "td-0039:booking"
    ],
    "/courses/raccoon-hill-golf-club-kent-oh/": [
      "td-0123:rate_source",
      "td-0123:booking",
      "td-0039:booking",
      "td-0040:booking"
    ],
    "/courses/eaglesticks-golf-club-zanesville-oh/": [
      "td-0076:rate_source",
      "td-0076:booking",
      "td-0080:course_info"
    ],
    "/courses/crystal-springs-golf-club-hopewell-oh/": [
      "td-0077:rate_source",
      "td-0077:booking"
    ],
    "/courses/the-virtues-golf-club-nashport-oh/": [
      "td-0078:rate_source",
      "td-0078:booking"
    ],
    "/courses/vista-golf-course-nashport-oh/": [
      "td-0081:rate_source",
      "td-0081:booking"
    ],
    "/courses/wildfire-golf-club-new-concord-oh/": [
      "td-0098:rate_source",
      "td-0098:course_info",
      "td-0080:course_info"
    ],
    "/courses/deer-ridge-golf-club-bellville-oh/": [
      "td-0048:rate_source",
      "td-0048:booking",
      "td-0047:course_info"
    ],
    "/courses/little-apple-golf-course-bellville-oh/": [
      "td-0110:rate_source",
      "td-0110:booking",
      "td-0047:course_info"
    ],
    "/courses/brookside-golf-course-ashland-oh/": [
      "td-0115:rate_source",
      "td-0115:booking",
      "td-0117:booking"
    ],
    "/courses/ashland-golf-club-ashland-oh/": [
      "td-0116:rate_source",
      "td-0116:booking",
      "td-0047:course_info"
    ],
    "/courses/forest-hills-golf-course-mansfield-oh/": [
      "td-0118:rate_source",
      "td-0118:booking"
    ],
    "/courses/twin-lakes-golf-club-mansfield-oh/": [
      "td-0124:rate_source",
      "td-0124:course_info",
      "td-0117:booking"
    ],
    "/courses/pine-hills-golf-club-hinckley-oh/": [
      "td-0042:rate_source",
      "td-0042:booking"
    ],
    "/courses/bunker-hill-golf-course-medina-oh/": [
      "td-0043:rate_source",
      "td-0043:booking"
    ],
    "/courses/coppertop-golf-club-valley-city-oh/": [
      "td-0044:rate_source",
      "td-0044:booking"
    ],
    "/courses/ironwood-golf-course-hinckley-oh/": [
      "td-0055:rate_source",
      "td-0055:booking"
    ],
    "/courses/shale-creek-golf-club-medina-oh/": [
      "td-0061:rate_source",
      "td-0061:booking"
    ],
    "/courses/valleaire-golf-club-hinckley-oh/": [
      "td-0062:rate_source",
      "td-0062:booking"
    ],
    "/courses/hinckley-hills-golf-course-hinckley-oh/": [
      "td-0065:rate_source",
      "td-0065:booking"
    ],
    "/courses/cossett-creek-golf-course-brunswick-oh/": [
      "td-0066:rate_source",
      "td-0066:booking"
    ],
    "/courses/denison-golf-club-granville-oh/": [
      "td-0087:rate_source",
      "td-0087:booking"
    ],
    "/courses/mastodon-golf-club-heath-oh/": [
      "td-0088:rate_source",
      "td-0088:booking",
      "td-0097:booking"
    ],
    "/courses/raccoon-valley-golf-club-granville-oh/": [
      "td-0089:rate_source",
      "td-0089:booking"
    ],
    "/courses/the-links-at-echo-springs-johnstown-oh/": [
      "td-0090:rate_source",
      "td-0090:booking"
    ],
    "/courses/cumberland-trail-golf-club-pataskala-oh/": [
      "td-0091:rate_source",
      "td-0091:booking",
      "td-0101:booking"
    ],
    "/courses/clover-valley-golf-club-johnstown-oh/": [
      "td-0094:rate_source",
      "td-0094:booking"
    ],
    "/courses/kyber-run-golf-course-johnstown-oh/": [
      "td-0095:rate_source",
      "td-0095:booking"
    ],
    "/courses/irish-hills-golf-club-mount-vernon-oh/": [
      "td-0092:rate_source",
      "td-0092:booking"
    ],
    "/courses/apple-valley-golf-club-howard-oh/": [
      "td-0114:rate_source",
      "td-0114:booking"
    ],
    "/courses/vernon-view-golf-course-mount-vernon-oh/": [
      "td-0119:rate_source",
      "td-0119:booking"
    ],
    "/courses/chapel-hill-golf-course-mount-vernon-oh/": [
      "td-0120:rate_source",
      "td-0120:booking"
    ],
    "/courses/manakiki-golf-course-willoughby-hills-oh/": [
      "td-0049:rate_source",
      "td-0049:booking"
    ],
    "/courses/st-denis-golf-club-chardon-oh/": [
      "td-0053:rate_source",
      "td-0053:booking"
    ],
    "/courses/fowler-s-mill-golf-course-chesterland-oh/": [
      "td-0067:rate_source",
      "td-0067:booking"
    ],
    "/courses/painesville-country-club-painesville-oh/": [
      "td-0068:rate_source",
      "td-0068:booking"
    ],
    "/courses/pleasant-hill-golf-course-chardon-chardon-oh/": [
      "td-0074:rate_source",
      "td-0074:booking"
    ]
  },
  "courses": {
    "td-0001": "Zoar Village Golf Course",
    "td-0002": "Oak Shadows Golf Club",
    "td-0003": "Wilkshire Golf Course",
    "td-0004": "River Greens Golf Course",
    "td-0005": "Hickory Flats Golf Course",
    "td-0006": "The Legends of Massillon",
    "td-0007": "Five Waters Golf Course",
    "td-0008": "Big Bend Golf Course",
    "td-0009": "Black Gold Golf Club",
    "td-0010": "The Quarry Golf Club and Venue",
    "td-0011": "Carroll Meadows Golf Course",
    "td-0012": "Great Trail Golf Course",
    "td-0013": "Arrowhead Golf Club & Banquet Center",
    "td-0014": "Raintree Golf & Event Center",
    "td-0015": "Raymond C. Firestone Golf Course",
    "td-0016": "Sable Creek Golf Course",
    "td-0017": "Pleasant View Golf Club",
    "td-0018": "Fire Ridge Golf Course",
    "td-0019": "The Pines Golf Club",
    "td-0020": "Chippewa Golf Club",
    "td-0021": "Spring Valley Golf Course",
    "td-0022": "Clearview Golf Club",
    "td-0023": "Edgewater Golf Course",
    "td-0024": "The Elms Country Club",
    "td-0025": "Black Diamond Golf Course",
    "td-0026": "Mayfair Country Club",
    "td-0027": "Chenoweth Golf Course",
    "td-0028": "Mud Run Golf Course",
    "td-0029": "J. Edward Good Park Golf Course",
    "td-0030": "Meadowlake Golf Course",
    "td-0031": "Tannenhauf Golf Club",
    "td-0032": "Riceland Golf Course",
    "td-0033": "Round Lake Golf Course",
    "td-0034": "Salt Fork State Park Golf Course",
    "td-0035": "Mulligan Springs Golf Course",
    "td-0036": "Windmill Lakes Golf Club",
    "td-0037": "Turkeyfoot Lake Golf Links",
    "td-0038": "Brookledge Golf Club",
    "td-0039": "Fox Den Golf Course",
    "td-0040": "Roses Run Country Club",
    "td-0041": "Boulder Creek Golf Club",
    "td-0042": "Pine Hills Golf Club",
    "td-0043": "Bunker Hill Golf Course",
    "td-0044": "Coppertop Golf Club",
    "td-0045": "Grey Hawk Golf Club",
    "td-0046": "Sweetbriar Golf Club",
    "td-0047": "Pleasant Hill Golf Course",
    "td-0048": "Deer Ridge Golf Club",
    "td-0049": "Manakiki Golf Course",
    "td-0050": "The Flying B Golf Course",
    "td-0051": "Reserve Run Golf Course",
    "td-0052": "Sleepy Hollow Golf Course",
    "td-0053": "St. Denis Golf Club",
    "td-0054": "Big Met Golf Course",
    "td-0055": "Ironwood Golf Course",
    "td-0056": "Little Met Golf Course",
    "td-0057": "Mastick Woods Golf Course",
    "td-0058": "Seneca Golf Course",
    "td-0059": "Shawnee Hills Golf Course",
    "td-0060": "Washington Golf Course",
    "td-0061": "Shale Creek Golf Club",
    "td-0062": "Valleaire Golf Club",
    "td-0063": "Mallard Creek Golf Club",
    "td-0064": "Pine Brook Golf Links",
    "td-0065": "Hinckley Hills Golf Course",
    "td-0066": "Cossett Creek Golf Course",
    "td-0067": "Fowler's Mill Golf Course",
    "td-0068": "Painesville Country Club",
    "td-0069": "Mill Creek Golf Course",
    "td-0070": "Knoll Run Golf Course",
    "td-0071": "The Links at Firestone Farms",
    "td-0072": "Lake Milton Golf Club",
    "td-0073": "Lyons Den Golf",
    "td-0074": "Pleasant Hill Golf Course — Chardon",
    "td-0075": "Olde Dutch Mill Golf Course",
    "td-0076": "EagleSticks Golf Club",
    "td-0077": "Crystal Springs Golf Club",
    "td-0078": "The Virtues Golf Club",
    "td-0079": "Zanesville Jaycees Public Golf Course",
    "td-0080": "Fuller's Fairways",
    "td-0081": "Vista Golf Course",
    "td-0082": "Cadiz Country Club",
    "td-0083": "Beaver Creek Meadows Golf Course",
    "td-0084": "Turkana Golf Course",
    "td-0085": "Historic Highlands Golf Course",
    "td-0086": "East Palestine Country Club",
    "td-0087": "Denison Golf Club",
    "td-0088": "Mastodon Golf Club",
    "td-0089": "Raccoon Valley Golf Club",
    "td-0090": "The Links at Echo Springs",
    "td-0091": "Cumberland Trail Golf Club",
    "td-0092": "Irish Hills Golf Club",
    "td-0093": "Lancaster Golf Club",
    "td-0094": "Clover Valley Golf Club",
    "td-0095": "Kyber Run Golf Course",
    "td-0096": "Coyote Run Golf Course",
    "td-0097": "Harbor Hills Country Club",
    "td-0098": "Wildfire Golf Club",
    "td-0099": "Wick Recreation Area Par 3",
    "td-0100": "Wilson Road Golf Course",
    "td-0101": "Blacklick Woods Golf Course",
    "td-0102": "Little Bear Golf Club",
    "td-0103": "Robin’s Nest Par 3",
    "td-0104": "Little Miami Golf Center",
    "td-0105": "Meadow Links & Golf Academy",
    "td-0106": "Green Hills Golf Course",
    "td-0107": "Wee Links at SportsOhio",
    "td-0108": "Fernbank Golf Course",
    "td-0109": "Reeves Golf Course",
    "td-0110": "Little Apple Golf Course",
    "td-0111": "Armco Park Golf Course",
    "td-0112": "Meadowood Golf Course",
    "td-0113": "L.C. Boles Memorial Golf Course",
    "td-0114": "Apple Valley Golf Club",
    "td-0115": "Brookside Golf Course",
    "td-0116": "Ashland Golf Club",
    "td-0117": "Oak Tree Golf Club",
    "td-0118": "Forest Hills Golf Course",
    "td-0119": "Vernon View Golf Course",
    "td-0120": "Chapel Hill Golf Course",
    "td-0121": "Paradise Lake Country Club",
    "td-0122": "The Fairways at Twin Lakes",
    "td-0123": "Raccoon Hill Golf Club",
    "td-0124": "Twin Lakes Golf Club"
  },
  "facilities": {
    "indoor-0001": "Beers and Birdies",
    "indoor-0002": "Willie's Custom Golf Center",
    "indoor-0003": "Under Par Indoor Golf",
    "indoor-0004": "Golf Garage Minerva",
    "indoor-0005": "Mishler Birdie Barn",
    "indoor-0006": "X-Golf North Canton",
    "indoor-0007": "Tee It Up Canton",
    "indoor-0008": "The Back Nine Golf - North Canton",
    "indoor-0009": "The Back Nine Golf - Wooster",
    "indoor-0010": "Ohio Golf Club",
    "indoor-0011": "Tee Time Anytime",
    "indoor-0012": "X-Golf Fairlawn",
    "indoor-0013": "The Corner Club",
    "indoor-0014": "1899 Indoor Golf"
  }
};
