import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { renderAreaGuide } from './new-philadelphia-prototype.mjs';
import { refineCourseDetail } from './course-detail-refinements.mjs';

// Read the existing trusted data declaration at build time. Never execute the
// browser application or maintain a second copy of prices and outbound URLs.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const source = read('app.js').replace(/\r\n/g, '\n');
const end = source.indexOf('\n];');
assert(end > 0 && source.startsWith('const courses = ['), 'Course declaration changed; review extraction');
const courses = JSON.parse(JSON.stringify(vm.runInNewContext(source.slice(0, end + 3) + '\ncourses;', {}, { timeout: 1000 })));
const registry = JSON.parse(read('seo/course-registry.json'));
const config = JSON.parse(read('seo/phase-one.json'));
const origin = 'https://www.playteedrop.com';
const check = process.argv.includes('--check');
assert.equal(courses.length, 124, 'Phase 1 must preserve all 124 records');
assert.equal(registry.length, courses.length);
for (const key of ['id', 'slug']) assert.equal(new Set(registry.map(r => r[key])).size, registry.length, `Duplicate ${key}`);
const byId = new Map(registry.map(r => {
  assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.slug), 'Unsafe slug');
  const matches = courses.filter(c => c.name === r.name && c.city === r.city);
  assert.equal(matches.length, 1, `Resolve ambiguous identity manually: ${r.name}, ${r.city}`);
  return [r.id, { ...matches[0], id: r.id, slug: r.slug }];
}));
assert.equal(new Set(registry.map(r => `${r.name}\0${r.city}`)).size, courses.length);
assert.equal(config.pilots.length, 8);
assert.equal(new Set(config.pilots).size, 8);
assert.equal(config.areas.length, 3);
const get = id => { assert(byId.has(id), `Unknown stable course ID: ${id}`); return byId.get(id); };
config.pilots.forEach(get);
for (const area of config.areas) {
  const ids = area.groups.flatMap(g => g.courses);
  assert.equal(new Set(ids).size, ids.length, `Duplicate course in ${area.name}`);
  ids.forEach(get);
}
const esc = value => String(value).replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
const href = value => { const url = new URL(value, origin); assert(['https:', 'http:'].includes(url.protocol)); return esc(value); };
const coursePath = c => `/courses/${c.slug}/`;
const areaPath = a => `/golf-courses/${a.slug}/`;
const isPilot = c => config.pilots.includes(c.id);
const closed = c => c.rateInfo?.status === 'closed';
const button = c => closed(c) ? 'Updates / Info' : c.bookingLabel ? 'Call / Info' : 'View Booking';
const note = c => closed(c) ? c.bookingNote : c.firstAvailable?.note || c.bookingNote || '';
// Full undated summaries preserve warnings intentionally shortened on home cards.
const summary = c => c.rateInfo.status === 'undated' ? c.rateInfo.summary : c.rateInfo.publicSummary || c.rateInfo.summary;
const status = c => c.rateInfo.statusLabel || 'Confirm rates with course';
const dateLabel = checked => {
  const date = new Date(checked + ' 12:00:00 UTC');
  assert(!Number.isNaN(date.valueOf()), `Invalid review date: ${checked}`);
  return `<time datetime="${date.toISOString().slice(0, 10)}">${esc(checked)}</time>`;
};
const external = (url, text, css = '') => `<a${css ? ` class="${css}"` : ''} href="${href(url)}" target="_blank" rel="noopener noreferrer">${esc(text)}<span class="visually-hidden"> (opens in a new tab)</span></a>`;
const action = c => external(c.bookingUrl, button(c), 'book-link seo-outbound');
const publisher = { '@type': 'Organization', '@id': origin + '/#organization', name: 'Tee Drop', url: origin + '/' };
function breadcrumb(items) {
  return { '@type': 'BreadcrumbList', itemListElement: items.map((i, n) => ({ '@type': 'ListItem', position: n + 1, name: i.name, item: origin + i.path })) };
}
function crumbs(items) {
  return `<nav class="seo-breadcrumbs" aria-label="Breadcrumb"><ol>${items.map((i, n) => `<li>${n === items.length - 1 ? `<span aria-current="page">${esc(i.name)}</span>` : `<a href="${href(i.path)}">${esc(i.name)}</a>`}</li>`).join('')}</ol></nav>`;
}
function shell({ title, description, url, items, graph, body }) {
  return `<!DOCTYPE html>
<!-- Generated by scripts/build-seo.mjs. Edit the source data/templates, then rebuild. -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <link rel="canonical" href="${origin}${url}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:url" content="${origin}${url}">
  <meta property="og:type" content="website">
  <meta name="theme-color" content="#164832">
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/styles.css?v=tee-drop-logo-20260805">
  <link rel="stylesheet" href="/seo.css?v=phase-one-20260912">
  <script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': [...graph, breadcrumb(items)] }, null, 2).replace(/</g, '\\u003c')}</script>
</head>
<body class="homepage seo-page">
  <a class="seo-skip" href="#main-content">Skip to content</a>
  <div class="app-shell">
    <header class="site-header">
      <a class="site-brand" href="/" aria-label="Tee Drop home"><picture class="brand-mark"><source media="(max-width: 680px)" srcset="/brand-assets/tee-drop-logo-system/tee-drop-icon.svg"><img class="brand-logo" src="/brand-assets/tee-drop-logo-system/tee-drop-horizontal-light.svg" alt="Tee Drop"></picture></a>
      <nav class="site-nav" aria-label="Primary navigation"><a href="/#courseDirectory">Find a Course</a><a href="/#area-guides">Area Guides</a><a href="/indoor.html">Indoor Golf</a><a href="/about.html">About</a></nav>
    </header>
    ${crumbs(items)}
    <main id="main-content" tabindex="-1">${body}</main>
    <footer class="site-footer"><div class="footer-brand"><img src="/brand-assets/tee-drop-logo-system/tee-drop-horizontal.svg" alt="Tee Drop"><p>An independent Ohio public-golf directory. Tee Drop is not the course owner or booking provider.</p></div><div class="footer-links"><a href="/">Explore the full directory</a><a href="/about.html">About Tee Drop</a><p>Rates and availability can change. Confirm details with the course before making plans. Outbound links open in a new tab.</p></div></footer>
  </div>
</body>
</html>
`.replace(/[ \t]+$/gm, '');
}
function review(c) {
  return `<p class="seo-review">Tee Drop rate review: ${dateLabel(c.rateInfo.checked)}. ${external(c.rateInfo.sourceUrl, 'Rate source')}</p>`;
}
function card(c) {
  return `<article class="seo-course-card" id="${c.id}">
    <p class="course-meta">${esc(c.city)}</p><h3>${isPilot(c) ? `<a href="${coursePath(c)}">${esc(c.name)}</a>` : esc(c.name)}</h3>
    <p class="seo-status${closed(c) ? ' seo-closed' : ''}">${esc(status(c))}${c.rateInfo.status === 'undated' ? ' · Undated source; confirm current pricing' : ''}</p>
    <p class="rate-info">${esc(summary(c))}</p>${review(c)}
    ${note(c) ? `<p class="seo-course-note">${esc(note(c))}</p>` : ''}
    <div class="seo-card-actions">${action(c)}${isPilot(c) ? `<a class="seo-detail" href="${coursePath(c)}">Course details<span class="visually-hidden">: ${esc(c.name)}</span></a>` : ''}</div>
  </article>`;
}
function areaNav(current) {
  return `<section class="seo-section" aria-labelledby="nearby-areas"><p class="section-kicker">Keep exploring</p><h2 id="nearby-areas">${current ? 'Explore another area' : 'Explore area guides'}</h2><div class="seo-area-links">${config.areas.filter(a => a !== current).map(a => `<a href="${areaPath(a)}">${esc(a.name)} <span aria-hidden="true">→</span></a>`).join('')}<a href="/#courseDirectory">All Ohio courses <span aria-hidden="true">→</span></a></div></section>`;
}
const outputs = new Map();
for (const area of config.areas) {
  const url = areaPath(area);
  const ids = area.groups.flatMap(g => g.courses);
  const items = [{ name: 'Home', path: '/' }, { name: area.name + ' golf courses', path: url }];
  const list = { '@type': 'ItemList', '@id': origin + url + '#courses', numberOfItems: ids.length, itemListOrder: 'https://schema.org/ItemListUnordered', itemListElement: ids.map((id, n) => { const c = get(id); return { '@type': 'ListItem', position: n + 1, name: c.name, url: origin + (isPilot(c) ? coursePath(c) : url + '#' + c.id) }; }) };
  const graph = [{ '@type': 'CollectionPage', '@id': origin + url + '#webpage', url: origin + url, name: area.title, description: area.description, publisher, mainEntity: { '@id': list['@id'] }, dateModified: config.contentModified }, list];
  const body = renderAreaGuide(area, { get, esc, external, action, coursePath, isPilot, areaNav });
  outputs.set(url.slice(1) + 'index.html', shell({ title: area.title, description: area.description, url, items, graph, body }));
}
function distance(a, b) {
  const rad = n => n * Math.PI / 180;
  const h = Math.sin(rad(b.latitude - a.latitude) / 2) ** 2 + Math.cos(rad(a.latitude)) * Math.cos(rad(b.latitude)) * Math.sin(rad(b.longitude - a.longitude) / 2) ** 2;
  return 3958.8 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}
for (const id of config.pilots) {
  const c = get(id), url = coursePath(c);
  const parents = config.areas.filter(a => a.groups.some(g => g.courses.includes(id)));
  // A course's existing region chooses between overlapping guides; never assign
  // an unrelated parent merely because every page needs a breadcrumb.
  const parent = parents.find(a => c.area === 'Canton / Stark County' && a.slug === 'canton-oh') || parents[0];
  const ending = closed(c) ? 'Closure Updates & Info' : c.bookingLabel ? 'Rates & Course Info' : 'Rates & Booking';
  const title = `${c.name} ${ending} | Tee Drop`;
  const description = closed(c) ? `${c.name} in ${c.city}: temporarily closed until further notice after July 5, 2026 storm damage. See Tee Drop’s record and official updates.` : `${c.name} in ${c.city}: Tee Drop’s rate notes, review date, important qualifications and ${c.bookingLabel ? 'course information link' : 'direct booking link'}.`;
  const items = [{ name: 'Home', path: '/' }, ...(parent ? [{ name: parent.name, path: areaPath(parent) }] : []), { name: c.name, path: url }];
  const courseEntity = { '@type': 'GolfCourse', '@id': origin + url + '#course', name: c.name, description: `${c.name} is listed in Tee Drop’s public-golf directory with a location of ${c.city}.${closed(c) ? ' Temporarily closed until further notice following July 5, 2026 storm damage.' : ''}` };
  const graph = [{ '@type': 'WebPage', '@id': origin + url + '#webpage', url: origin + url, name: title, description, publisher, mainEntity: { '@id': courseEntity['@id'] }, dateModified: config.contentModified }, courseEntity];
  const nearby = [...byId.values()].filter(other => other.id !== id).map(other => ({ course: other, miles: distance(c, other) })).filter(n => n.miles <= 25).sort((a, b) => a.miles - b.miles || a.course.id.localeCompare(b.course.id)).slice(0, 3);
  const characteristics = [];
  if (c.courseType) characteristics.push(['Course type', ({ par3: 'Par 3', executive: 'Executive / short', regulation: 'Regulation' })[c.courseType]]);
  if (Number.isInteger(c.holes)) characteristics.push(['Holes', String(c.holes)]);
  // Notes remain prose: never mine them for structured addresses/phone/amenities.
  let body = `<section class="seo-hero"><p class="section-kicker">Ohio public golf · Course guide</p><h1>${esc(c.name)}</h1><p class="seo-lead">${esc(c.city)}</p><p class="seo-hero-meta">Independent course information from Tee Drop</p></section>
    <div class="seo-detail-layout"><section class="seo-rate-panel" aria-labelledby="rates-title"><p class="section-kicker">${closed(c) ? 'Course status' : 'Plan your round'}</p><h2 id="rates-title">${closed(c) ? 'Temporarily closed' : 'Rates & important details'}</h2><p class="seo-status${closed(c) ? ' seo-closed' : ''}">${esc(status(c))}${c.rateInfo.status === 'undated' ? ' · Undated source; confirm current pricing' : ''}</p><p class="rate-info seo-full-rate">${esc(summary(c))}</p>${review(c)}${note(c) ? `<div class="seo-notice"><h3>${closed(c) ? 'Reopening information' : 'Before you go'}</h3><p>${esc(note(c))}</p></div>` : ''}<p class="seo-small">${closed(c) ? 'This listing remains available for closure information. Check the official update before planning a visit.' : 'Rates are not live availability. Confirm current prices, cart terms and any restrictions directly with the course.'}</p></section>
    <aside class="seo-action-panel" aria-labelledby="course-link-title"><p class="section-kicker">Direct course link</p><h2 id="course-link-title">${closed(c) ? 'Follow reopening updates' : c.bookingLabel ? 'Contact the course' : 'Check tee times'}</h2><p>${closed(c) ? 'The course is temporarily closed. Use its official information page for updates.' : c.bookingLabel ? 'Use the course’s information page to confirm availability and rates.' : c.name === 'Sweetbriar Golf Club' ? 'Choose from the course’s booking options on its official booking page.' : 'Availability and reservations are handled by the course or its booking provider.'}</p>${action(c)}<p class="seo-small">You’ll leave Tee Drop. Opens in a new tab.</p>${parents.length ? `<div class="seo-parent-links"><h3>Explore this area</h3>${parents.map(a => `<a href="${areaPath(a)}">${esc(a.name)} golf courses</a>`).join('')}</div>` : '<p><a href="/#courseDirectory">Back to all Ohio courses</a></p>'}</aside></div>
    <section class="seo-facts seo-section"><h2>About this listing</h2><p>${esc(courseEntity.description)} Tee Drop is an independent directory, not the course’s official website.</p>${characteristics.length ? `<dl>${characteristics.map(([k, v]) => `<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>` : ''}</section>
    <section class="seo-section" aria-labelledby="nearby-courses"><p class="section-kicker">More places to look</p><h2 id="nearby-courses">Nearby Tee Drop courses</h2><p>Nearby suggestions use the directory’s recorded coordinates, not driving times. Check each course’s own information before making plans.</p><ul class="seo-nearby">${nearby.map(({ course: n }) => `<li><div><strong>${isPilot(n) ? `<a href="${coursePath(n)}">${esc(n.name)}</a>` : esc(n.name)}</strong><span>${esc(n.city)}${closed(n) ? ' · Temporarily closed' : ''}</span></div>${isPilot(n) ? `<a class="seo-detail" href="${coursePath(n)}">Course details<span class="visually-hidden">: ${esc(n.name)}</span></a>` : external(n.bookingUrl, button(n), 'seo-detail')}</li>`).join('')}</ul></section>`;
  body = refineCourseDetail(c, body, { esc, external });
  outputs.set(url.slice(1) + 'index.html', shell({ title, description, url, items, graph, body }));
}

const discovery = `<!-- SEO DISCOVERY START -->
    <section class="seo-discovery" id="area-guides" aria-labelledby="area-guides-title">
      <div class="section-heading"><div><p class="section-kicker">Explore by place</p><h2 id="area-guides-title">Local golf guides</h2></div><p>Course locations, qualified rates and direct course links.</p></div>
      <div class="seo-area-links">${config.areas.map(a => `<a href="${areaPath(a)}">${esc(a.name)} <span aria-hidden="true">→</span></a>`).join('')}</div>
      <h3>Take a closer look at a course</h3>
      <ul class="seo-pilot-links">${config.pilots.map(id => { const c = get(id); return `<li><a href="${coursePath(c)}">${esc(c.name)}</a><span>${esc(c.city)}${closed(c) ? ' · Temporarily closed' : ''}</span></li>`; }).join('')}</ul>
      <noscript><p>Search and filters need JavaScript. The guides above provide course information and direct links without it.</p></noscript>
    </section>
    <!-- SEO DISCOVERY END -->`;
let home = read('index.html');
if (home.includes('<!-- SEO DISCOVERY START -->')) home = home.replace(/<!-- SEO DISCOVERY START -->[\s\S]*?<!-- SEO DISCOVERY END -->/, discovery);
else home = home.replace('    <button class="primary-action back-to-filters"', '    ' + discovery + '\n\n    <button class="primary-action back-to-filters"');
if (!home.includes('href="seo.css')) home = home.replace('</head>', '  <link rel="stylesheet" href="seo.css?v=phase-one-20260912">\n</head>');
assert(home.includes(discovery), 'Homepage insertion point missing');
outputs.set('index.html', home);
const pages = [...config.existingPages, ...config.areas.map(a => ({ path: areaPath(a), lastmod: config.contentModified })), ...config.pilots.map(id => ({ path: coursePath(get(id)), lastmod: config.contentModified }))];
assert.equal(pages.length, 14);
outputs.set('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p => `  <url><loc>${origin}${p.path}</loc><lastmod>${p.lastmod}</lastmod></url>`).join('\n')}\n</urlset>\n`);
let drift = false;
for (const [file, content] of outputs) {
  if (check) {
    if (!fs.existsSync(path.join(root, file)) || read(file) !== content) { console.error(`Stale generated file: ${file}`); drift = true; }
  } else {
    fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    if (!fs.existsSync(path.join(root, file)) || read(file) !== content) fs.writeFileSync(path.join(root, file), content);
  }
}
if (drift) process.exitCode = 1;
else console.log(`${check ? 'Verified' : 'Generated'} 3 area pages, 8 course pages, homepage discovery and 14 sitemap entries.`);
